SET SERVEROUTPUT ON;

CREATE TABLE ErrorLog (
    ErrorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ErrorMessage VARCHAR2(4000),
    ErrorDate DATE DEFAULT SYSDATE
);

-- =========================================
-- Scenario 1: SafeTransferFunds
-- =========================================

CREATE OR REPLACE PROCEDURE SafeTransferFunds(
    p_from_account IN NUMBER,
    p_to_account IN NUMBER,
    p_amount IN NUMBER
) AS
    v_balance NUMBER;
    insufficient_funds EXCEPTION;
BEGIN
    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID = p_from_account
    FOR UPDATE;

    IF v_balance < p_amount THEN
        RAISE insufficient_funds;
    END IF;

    UPDATE Accounts
    SET Balance = Balance - p_amount
    WHERE AccountID = p_from_account;

    UPDATE Accounts
    SET Balance = Balance + p_amount
    WHERE AccountID = p_to_account;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Transfer successful');

EXCEPTION
    WHEN insufficient_funds THEN
        ROLLBACK;

        INSERT INTO ErrorLog(ErrorMessage)
        VALUES('Insufficient funds in account ' || p_from_account);

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Insufficient funds');

    WHEN NO_DATA_FOUND THEN
        ROLLBACK;

        INSERT INTO ErrorLog(ErrorMessage)
        VALUES('Account not found');

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Account not found');

    WHEN OTHERS THEN
        ROLLBACK;

        INSERT INTO ErrorLog(ErrorMessage)
        VALUES(SQLERRM);

        COMMIT;

        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

BEGIN
    SafeTransferFunds(1, 2, 500);
END;
/

-- =========================================
-- Scenario 2: UpdateSalary
-- =========================================

CREATE OR REPLACE PROCEDURE UpdateSalary(
    p_employee_id IN NUMBER,
    p_percent IN NUMBER
) AS
BEGIN
    UPDATE Employees
    SET Salary = Salary + (Salary * p_percent / 100)
    WHERE EmployeeID = p_employee_id;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Salary updated');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO ErrorLog(ErrorMessage)
        VALUES('Employee not found: ' || p_employee_id);

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Employee not found');

    WHEN OTHERS THEN
        ROLLBACK;

        INSERT INTO ErrorLog(ErrorMessage)
        VALUES(SQLERRM);

        COMMIT;

        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

BEGIN
    UpdateSalary(1, 10);
END;
/

-- =========================================
-- Scenario 3: AddNewCustomer
-- =========================================

CREATE OR REPLACE PROCEDURE AddNewCustomer(
    p_customer_id IN NUMBER,
    p_name IN VARCHAR2,
    p_dob IN DATE,
    p_balance IN NUMBER
) AS
BEGIN
    INSERT INTO Customers(
        CustomerID,
        Name,
        DOB,
        Balance,
        LastModified
    )
    VALUES(
        p_customer_id,
        p_name,
        p_dob,
        p_balance,
        SYSDATE
    );

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Customer added');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        INSERT INTO ErrorLog(ErrorMessage)
        VALUES('Customer ID already exists: ' || p_customer_id);

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Duplicate customer ID');

    WHEN OTHERS THEN
        ROLLBACK;

        INSERT INTO ErrorLog(ErrorMessage)
        VALUES(SQLERRM);

        COMMIT;

        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

BEGIN
    AddNewCustomer(
        10,
        'New Customer',
        TO_DATE('2000-01-01','YYYY-MM-DD'),
        5000
    );
END;
/

SELECT * FROM ErrorLog;